// Generated by scripts/build.mjs — do not edit.
window.__ModuleLoader__.load({
	id: "dsh-plugin-model-capability",
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/client/index.jsx
var index_exports = {};
__export(index_exports, {
  apply: () => apply,
  inject: () => inject
});
module.exports = __toCommonJS(index_exports);

// src/client/dict.js
function localize(dicts2, lang, key, params) {
  let text = dicts2[lang]?.[key];
  if (text === void 0) text = dicts2.en[key];
  if (text === void 0) text = key;
  if (params !== void 0) {
    for (const [name, value] of Object.entries(params)) {
      text = text.split(`{${name}}`).join(String(value));
    }
  }
  return text;
}
var en = {
  nav: "Model Capability",
  pageIntro: "Manage the llm-pi-ai provider routes: per-model thinking levels, context / output capacity, input modalities, gateway compatibility, and route defaults. Edits are written to settings.yaml and validated by the Host.",
  writableHost: "Edits are persisted to settings.yaml.",
  notWritable: "Settings are read-only in this browser (remote access).",
  memoryMode: "This browser cannot persist settings (loopback required).",
  langField: "Page language",
  langFollow: "Follow DSH",
  langEn: "English",
  langZh: "\u4E2D\u6587",
  route: "Route",
  routeId: "Route ID",
  model: "Model",
  modelId: "Model ID",
  expand: "Expand",
  collapse: "Collapse",
  advanced: "Advanced",
  advancedFold: "Advanced fields",
  rawView: "Raw section (read-only)",
  modelName: "Display name",
  contextWindow: "Context window",
  maxTokens: "Max output",
  inputModalities: "Input modalities",
  modalityText: "text",
  modalityImage: "image",
  capacityHint: "e.g. 262144, 256K, 1M",
  remove: "Remove",
  thinkingEnabled: "This model supports thinking (reasoning efforts)",
  thinkingHint: "Key = selectable level, value = the wire spelling sent for that level. Only 'off' may stay empty (send nothing).",
  levelOff: "off",
  levelMinimal: "minimal",
  levelLow: "low",
  levelMedium: "medium",
  levelHigh: "high",
  levelXhigh: "xhigh",
  levelMax: "max",
  offPlaceholder: "nothing is sent",
  wirePlaceholder: "wire value",
  fillLevels: "Fill all levels with their own name",
  reasoningFalseHint: "Setting thinking off stores reasoningEfforts: false \u2014 DSH will not offer thinking levels for this model.",
  reasoningNeedsOneLevel: "At least one thinking level besides 'off' needs a wire value.",
  compatTitle: "Gateway compatibility",
  compatIntro: "compat fields describe what the gateway understands. Mismatches are the most common cause of 400 errors (e.g. the message role 'developer').",
  applyToAllModels: "Apply this model's settings to all models in this route",
  applied: "Applied",
  modelCompat: "Per-model compat",
  defaultsTitle: "Route defaults",
  defaultsIntro: "Fallbacks used for models/turns that do not declare a value.",
  defaultContextWindow: "Default context window",
  defaultMaxTokens: "Default max output",
  defaultInput: "Default input modalities",
  reasoningDefault: "Default thinking level",
  thinkingBudgets: "Thinking budgets (chars)",
  cacheRetention: "Prompt-cache retention",
  transport: "Stream transport",
  headers: "Extra headers",
  headerKey: "Header",
  headerValue: "Value",
  addHeader: "Add header",
  apiKeyEnv: "API key environment variable",
  baseURL: "Base URL",
  api: "API protocol",
  displayName: "Display name",
  timeoutMs: "Request timeout (ms)",
  websocketConnectTimeoutMs: "WebSocket connect timeout (ms)",
  streamIdleTimeoutMs: "Stream idle timeout (ms)",
  maxRequestImageBytes: "Max request image bytes",
  requestImagePixelBudget: "Image pixel budget",
  requestImageMaxBytes: "Max inline image bytes",
  transportSse: "sse",
  transportWebsocket: "websocket",
  transportWebsocketCached: "websocket-cached",
  transportAuto: "auto",
  cacheNone: "none",
  cacheShort: "short",
  cacheLong: "long",
  // Compat field labels
  supportsDeveloperRole: "Accepts the 'developer' message role",
  supportsDeveloperRoleHint: "Off for older gateways (DashScope / Kimi / Zhipu / MiniMax / SiliconFlow \u2026) that only understand 'system'.",
  supportsReasoningEffort: "Accepts a reasoning_effort parameter",
  supportsStore: "Accepts a 'store' flag",
  supportsUsageInStreaming: "Reports usage in streaming chunks",
  supportsTemperature: "Accepts temperature",
  supportsStrictMode: "Supports strict JSON mode",
  supportsStrictTools: "Supports strict tool schemas",
  supportsLongCacheRetention: "Supports long cache retention",
  supportsEagerToolInputStreaming: "Streams tool input eagerly",
  supportsCacheControlOnTools: "Supports cache_control on tools",
  requiresToolResultName: "Requires a name on tool results",
  requiresAssistantAfterToolResult: "Requires assistant msgs after tool results",
  requiresThinkingAsText: "Thinks via plain text",
  requiresReasoningContentOnAssistantMessages: "Needs reasoning_content on assistant messages",
  forceAdaptiveThinking: "Force adaptive thinking",
  allowEmptySignature: "Allows empty signatures",
  thinkingFormat: "Thinking wire format (dialect)",
  maxTokensField: "Max-output wire field",
  cacheControlFormat: "Cache-control format",
  // Presets
  presetTitle: "One-click presets",
  presetIntro: "Apply a curated configuration to selected routes in one click (writes are validated by the Host).",
  builtinsTitle: "Built-in recipes",
  builtinSafeGateway: "Safe gateway mode",
  builtinSafeGatewayDesc: "compat: supportsDeveloperRole=false \u2014 for gateways that reject the 'developer' role (DashScope, Kimi, Zhipu, MiniMax \u2026).",
  builtinOpenaiNative: "OpenAI-native",
  builtinOpenaiNativeDesc: "compat: developer role on, thinkingFormat=openai, maxTokensField=max_completion_tokens.",
  builtinDeepseekDialect: "DeepSeek dialect",
  builtinDeepseekDialectDesc: "compat: thinkingFormat=deepseek, developer role on.",
  builtinQwenDialect: "Qwen dialect",
  builtinQwenDialectDesc: "compat: thinkingFormat=qwen, developer role off.",
  builtinMaxThinking: "Max thinking (7 levels)",
  builtinMaxThinkingDesc: "Declare all seven thinking levels (off\u2192max) on every model and set high default thinking.",
  builtinTextOnly: "Text-only",
  builtinTextOnlyDesc: "Input modalities = text everywhere.",
  builtinImageReady: "Text + image",
  builtinImageReadyDesc: "Input modalities = text + image everywhere.",
  presetRoutes: "Apply to routes",
  selectAll: "Select all",
  deselectAll: "Deselect all",
  applyPreset: "Apply",
  cancel: "Cancel",
  presetApplied: "Preset applied.",
  presetFailed: "Preset was rejected by the settings service:",
  savePreset: "Save current settings as a preset",
  savePresetName: "Preset name",
  savePresetBlurb: "Stores a snapshot of the current llm-pi-ai user section into the model-capability settings namespace.",
  savePresetBtn: "Save preset",
  noUserRoutesHint: "Nothing to save \u2014 no routes have been edited yet.",
  presetSaved: "Preset saved.",
  customPresetsTitle: "My presets",
  presetEmpty: "No custom presets yet.",
  applyCustom: "Apply (replaces the current llm-pi-ai user section)",
  deleteCustom: "Delete",
  confirmApplyCustom: "Apply this preset? It replaces the current user section of the llm-pi-ai settings.",
  confirmDeleteCustom: "Delete this preset?",
  presetCorrupt: "This preset contains invalid data and could not be applied.",
  presetNotFound: "Preset not found.",
  // Diagnostics
  diagTitle: "Advisory checks",
  diagNone: "No advisories for the current configuration.",
  diagDeveloperRole: "{route}: baseURL looks like a legacy gateway but compat.supportsDeveloperRole is on \u2014 safe-gateway preset or manual off avoids 400 errors.",
  diagEmptyEffort: "{route} / {model}: reasoningEfforts.{level} is empty (only 'off' may send nothing) \u2014 the Host will reject the write.",
  diagLooseEfforts: "{route} / {model}: declares reasoningEfforts but thinking is disabled for the model entry (reasoningEfforts: false keeps it disabled).",
  diagNoContext: "{route} / {model}: no contextWindow \u2014 DSH falls back to the route default.",
  diagNoModels: "{route}: declares no models \u2014 the route serves its built-in catalog.",
  // Status / errors
  conflict: "Another change landed first (settings conflict). The page reloaded your view \u2014 please re-apply any draft.",
  writeFailed: "Write was rejected:",
  routeNotFound: "Route not found in the resolved settings.",
  modelNotFound: "Model not found in this route.",
  unknownError: "Unexpected failure.",
  // Generic
  show: "Show",
  hide: "Hide",
  on: "on",
  off: "off"
};
var zh = {
  nav: "\u6A21\u578B\u80FD\u529B",
  pageIntro: "\u7BA1\u7406 llm-pi-ai \u63D0\u4F9B\u5546\u8DEF\u7531:\u6BCF\u4E2A\u6A21\u578B\u7684\u601D\u8003\u7B49\u7EA7\u3001\u4E0A\u4E0B\u6587/\u8F93\u51FA\u5BB9\u91CF\u3001\u8F93\u5165\u6A21\u6001\u3001\u7F51\u5173\u517C\u5BB9\u6027\u548C\u8DEF\u7531\u9ED8\u8BA4\u503C\u3002\u4FEE\u6539\u4F1A\u5199\u5165 settings.yaml \u5E76\u7ECF Host \u6821\u9A8C\u3002",
  writableHost: "\u4FEE\u6539\u4F1A\u6301\u4E45\u5316\u5230 settings.yaml\u3002",
  notWritable: "\u6B64\u6D4F\u89C8\u5668\u4E2D\u8BBE\u7F6E\u4E3A\u53EA\u8BFB(\u8FDC\u7A0B\u8BBF\u95EE)\u3002",
  memoryMode: "\u6B64\u6D4F\u89C8\u5668\u65E0\u6CD5\u6301\u4E45\u5316\u8BBE\u7F6E(\u9700\u8981\u672C\u673A\u56DE\u73AF\u8BBF\u95EE)\u3002",
  langField: "\u9875\u9762\u8BED\u8A00",
  langFollow: "\u8DDF\u968F DSH",
  langEn: "English",
  langZh: "\u4E2D\u6587",
  route: "\u8DEF\u7531",
  routeId: "\u8DEF\u7531 ID",
  model: "\u6A21\u578B",
  modelId: "\u6A21\u578B ID",
  expand: "\u5C55\u5F00",
  collapse: "\u6536\u8D77",
  advanced: "\u9AD8\u7EA7",
  advancedFold: "\u9AD8\u7EA7\u5B57\u6BB5",
  rawView: "\u539F\u59CB\u914D\u7F6E\u6BB5(\u53EA\u8BFB)",
  modelName: "\u663E\u793A\u540D\u79F0",
  contextWindow: "\u4E0A\u4E0B\u6587\u7A97\u53E3",
  maxTokens: "\u6700\u5927\u8F93\u51FA",
  inputModalities: "\u8F93\u5165\u6A21\u6001",
  modalityText: "\u6587\u672C",
  modalityImage: "\u56FE\u50CF",
  capacityHint: "\u4F8B:262144\u3001256K\u30011M",
  remove: "\u5220\u9664",
  thinkingEnabled: "\u8BE5\u6A21\u578B\u652F\u6301\u601D\u8003(\u63A8\u7406\u7B49\u7EA7)",
  thinkingHint: "\u952E = \u53EF\u9009\u7B49\u7EA7,\u503C = \u8BE5\u7B49\u7EA7\u53D1\u9001\u5230\u7F51\u5173\u7684\u7EBF\u4E0A\u53C2\u6570\u3002\u53EA\u6709 off \u53EF\u4EE5\u7559\u7A7A(\u8868\u793A\u4E0D\u53D1\u9001)\u3002",
  levelOff: "off",
  levelMinimal: "minimal",
  levelLow: "low",
  levelMedium: "medium",
  levelHigh: "high",
  levelXhigh: "xhigh",
  levelMax: "max",
  offPlaceholder: "\u4E0D\u53D1\u9001\u5185\u5BB9",
  wirePlaceholder: "\u7EBF\u4E0A\u503C",
  fillLevels: "\u5168\u90E8\u7B49\u7EA7\u586B\u4E3A\u540C\u540D",
  reasoningFalseHint: "\u5173\u95ED\u601D\u8003\u4F1A\u5199\u5165 reasoningEfforts: false\u2014\u2014DSH \u5C06\u4E0D\u518D\u4E3A\u8BE5\u6A21\u578B\u63D0\u4F9B\u601D\u8003\u7B49\u7EA7\u9009\u9879\u3002",
  reasoningNeedsOneLevel: "\u9664 off \u4E4B\u5916\u81F3\u5C11\u9700\u8981\u4E00\u4E2A\u601D\u8003\u7B49\u7EA7\u5E76\u586B\u5199\u7EBF\u4E0A\u503C\u3002",
  compatTitle: "\u7F51\u5173\u517C\u5BB9\u6027",
  compatIntro: "compat \u5B57\u6BB5\u63CF\u8FF0\u7F51\u5173\u80FD\u7406\u89E3\u4EC0\u4E48\u3002\u4E0D\u5339\u914D\u662F 400 \u62A5\u9519\u6700\u5E38\u89C1\u7684\u6765\u6E90(\u4F8B\u5982\u6D88\u606F\u89D2\u8272 'developer')\u3002",
  applyToAllModels: "\u628A\u672C\u6A21\u578B\u8BBE\u7F6E\u5E94\u7528\u5230\u672C\u8DEF\u7531\u5168\u90E8\u6A21\u578B",
  applied: "\u5DF2\u5E94\u7528",
  modelCompat: "\u6A21\u578B\u7EA7\u517C\u5BB9",
  defaultsTitle: "\u8DEF\u7531\u9ED8\u8BA4\u503C",
  defaultsIntro: "\u6A21\u578B/\u8BF7\u6C42\u672A\u58F0\u660E\u65F6\u7684\u56DE\u9000\u503C\u3002",
  defaultContextWindow: "\u9ED8\u8BA4\u4E0A\u4E0B\u6587\u7A97\u53E3",
  defaultMaxTokens: "\u9ED8\u8BA4\u6700\u5927\u8F93\u51FA",
  defaultInput: "\u9ED8\u8BA4\u8F93\u5165\u6A21\u6001",
  reasoningDefault: "\u9ED8\u8BA4\u601D\u8003\u7B49\u7EA7",
  thinkingBudgets: "\u601D\u8003\u9884\u7B97(\u5B57\u7B26)",
  cacheRetention: "\u63D0\u793A\u8BCD\u7F13\u5B58\u4FDD\u7559",
  transport: "\u6D41\u5F0F\u4F20\u8F93\u65B9\u5F0F",
  headers: "\u989D\u5916\u8BF7\u6C42\u5934",
  headerKey: "\u8BF7\u6C42\u5934",
  headerValue: "\u503C",
  addHeader: "\u6DFB\u52A0\u8BF7\u6C42\u5934",
  apiKeyEnv: "API \u5BC6\u94A5\u73AF\u5883\u53D8\u91CF\u540D",
  baseURL: "Base URL",
  api: "API \u534F\u8BAE",
  displayName: "\u663E\u793A\u540D\u79F0",
  timeoutMs: "\u8BF7\u6C42\u8D85\u65F6(ms)",
  websocketConnectTimeoutMs: "WebSocket \u8FDE\u63A5\u8D85\u65F6(ms)",
  streamIdleTimeoutMs: "\u6D41\u7A7A\u95F2\u8D85\u65F6(ms)",
  maxRequestImageBytes: "\u6700\u5927\u8BF7\u6C42\u56FE\u7247\u5B57\u8282\u6570",
  requestImagePixelBudget: "\u56FE\u7247\u50CF\u7D20\u9884\u7B97",
  requestImageMaxBytes: "\u6700\u5927\u5185\u8054\u56FE\u7247\u5B57\u8282\u6570",
  transportSse: "sse",
  transportWebsocket: "websocket",
  transportWebsocketCached: "websocket-cached",
  transportAuto: "auto",
  cacheNone: "none",
  cacheShort: "short",
  cacheLong: "long",
  supportsDeveloperRole: "\u63A5\u53D7 'developer' \u6D88\u606F\u89D2\u8272",
  supportsDeveloperRoleHint: "\u65E7\u5F0F\u7F51\u5173(DashScope / Kimi / \u667A\u8C31 / MiniMax / \u7845\u57FA\u6D41\u52A8\u2026\u2026)\u53EA\u8BA4 'system',\u9700\u8981\u5173\u95ED\u3002",
  supportsReasoningEffort: "\u63A5\u53D7 reasoning_effort \u53C2\u6570",
  supportsStore: "\u63A5\u53D7 'store' \u6807\u8BB0",
  supportsUsageInStreaming: "\u6D41\u5F0F\u5206\u5757\u4E2D\u4E0A\u62A5\u7528\u91CF",
  supportsTemperature: "\u63A5\u53D7 temperature",
  supportsStrictMode: "\u652F\u6301\u4E25\u683C JSON \u6A21\u5F0F",
  supportsStrictTools: "\u652F\u6301\u4E25\u683C\u5DE5\u5177\u7ED3\u6784",
  supportsLongCacheRetention: "\u652F\u6301\u957F\u7F13\u5B58\u4FDD\u7559",
  supportsEagerToolInputStreaming: "\u5DE5\u5177\u8F93\u5165\u5373\u65F6\u6D41\u5F0F",
  supportsCacheControlOnTools: "\u5DE5\u5177\u4E0A\u652F\u6301 cache_control",
  requiresToolResultName: "\u5DE5\u5177\u7ED3\u679C\u9700\u8981 name",
  requiresAssistantAfterToolResult: "\u5DE5\u5177\u7ED3\u679C\u540E\u9700\u8981 assistant \u6D88\u606F",
  requiresThinkingAsText: "\u4EE5\u7EAF\u6587\u672C\u601D\u8003",
  requiresReasoningContentOnAssistantMessages: "assistant \u6D88\u606F\u9700\u8981 reasoning_content",
  forceAdaptiveThinking: "\u5F3A\u5236\u81EA\u9002\u5E94\u601D\u8003",
  allowEmptySignature: "\u5141\u8BB8\u7A7A\u7B7E\u540D",
  thinkingFormat: "\u601D\u8003\u7EBF\u4E0A\u683C\u5F0F(\u65B9\u8A00)",
  maxTokensField: "\u6700\u5927\u8F93\u51FA\u5B57\u6BB5",
  cacheControlFormat: "\u7F13\u5B58\u63A7\u5236\u683C\u5F0F",
  presetTitle: "\u4E00\u952E\u9884\u8BBE",
  presetIntro: "\u4E00\u952E\u628A\u7CBE\u9009\u914D\u7F6E\u5E94\u7528\u5230\u6240\u9009\u8DEF\u7531(\u5199\u5165\u7531 Host \u6821\u9A8C)\u3002",
  builtinsTitle: "\u5185\u7F6E\u914D\u65B9",
  builtinSafeGateway: "\u5B89\u5168\u7F51\u5173\u6A21\u5F0F",
  builtinSafeGatewayDesc: "compat: supportsDeveloperRole=false\u2014\u2014\u7ED9\u4E0D\u63A5\u53D7 'developer' \u89D2\u8272\u7684\u7F51\u5173(DashScope\u3001Kimi\u3001\u667A\u8C31\u3001MiniMax\u2026\u2026)\u4F7F\u7528\u3002",
  builtinOpenaiNative: "OpenAI \u539F\u751F",
  builtinOpenaiNativeDesc: "compat: \u5F00\u542F developer \u89D2\u8272\u3001thinkingFormat=openai\u3001maxTokensField=max_completion_tokens\u3002",
  builtinDeepseekDialect: "DeepSeek \u65B9\u8A00",
  builtinDeepseekDialectDesc: "compat: thinkingFormat=deepseek,\u5F00\u542F developer \u89D2\u8272\u3002",
  builtinQwenDialect: "Qwen \u65B9\u8A00",
  builtinQwenDialectDesc: "compat: thinkingFormat=qwen,\u5173\u95ED developer \u89D2\u8272\u3002",
  builtinMaxThinking: "\u5168\u529B\u601D\u8003(7 \u6863)",
  builtinMaxThinkingDesc: "\u4E3A\u6BCF\u4E2A\u6A21\u578B\u58F0\u660E\u5168\u90E8\u4E03\u4E2A\u601D\u8003\u7B49\u7EA7(off\u2192max),\u9ED8\u8BA4\u601D\u8003\u8BBE\u4E3A high\u3002",
  builtinTextOnly: "\u4EC5\u6587\u672C",
  builtinTextOnlyDesc: "\u6240\u6709\u4F4D\u7F6E\u8F93\u5165\u6A21\u6001 = text\u3002",
  builtinImageReady: "\u6587\u672C + \u56FE\u50CF",
  builtinImageReadyDesc: "\u6240\u6709\u4F4D\u7F6E\u8F93\u5165\u6A21\u6001 = text + image\u3002",
  presetRoutes: "\u5E94\u7528\u5230\u8DEF\u7531",
  selectAll: "\u5168\u9009",
  deselectAll: "\u5168\u4E0D\u9009",
  applyPreset: "\u5E94\u7528",
  cancel: "\u53D6\u6D88",
  presetApplied: "\u9884\u8BBE\u5DF2\u5E94\u7528\u3002",
  presetFailed: "\u9884\u8BBE\u88AB\u8BBE\u7F6E\u670D\u52A1\u62D2\u7EDD:",
  savePreset: "\u628A\u5F53\u524D\u8BBE\u7F6E\u4FDD\u5B58\u4E3A\u9884\u8BBE",
  savePresetName: "\u9884\u8BBE\u540D\u79F0",
  savePresetBlurb: "\u628A\u5F53\u524D llm-pi-ai \u7528\u6237\u914D\u7F6E\u6BB5\u5FEB\u7167\u5B58\u5165 model-capability \u8BBE\u7F6E\u547D\u540D\u7A7A\u95F4\u3002",
  savePresetBtn: "\u4FDD\u5B58\u9884\u8BBE",
  noUserRoutesHint: "\u6CA1\u6709\u53EF\u4FDD\u5B58\u7684\u5185\u5BB9\u2014\u2014\u8FD8\u6CA1\u6709\u7F16\u8F91\u8FC7\u4EFB\u4F55\u8DEF\u7531\u3002",
  presetSaved: "\u9884\u8BBE\u5DF2\u4FDD\u5B58\u3002",
  customPresetsTitle: "\u6211\u7684\u9884\u8BBE",
  presetEmpty: "\u8FD8\u6CA1\u6709\u81EA\u5B9A\u4E49\u9884\u8BBE\u3002",
  applyCustom: "\u5E94\u7528(\u66FF\u6362\u5F53\u524D llm-pi-ai \u7528\u6237\u914D\u7F6E\u6BB5)",
  deleteCustom: "\u5220\u9664",
  confirmApplyCustom: "\u5E94\u7528\u8BE5\u9884\u8BBE?\u5B83\u5C06\u66FF\u6362 llm-pi-ai \u8BBE\u7F6E\u7684\u5F53\u524D\u7528\u6237\u914D\u7F6E\u6BB5\u3002",
  confirmDeleteCustom: "\u5220\u9664\u8BE5\u9884\u8BBE?",
  presetCorrupt: "\u8BE5\u9884\u8BBE\u5305\u542B\u65E0\u6548\u6570\u636E,\u65E0\u6CD5\u5E94\u7528\u3002",
  presetNotFound: "\u672A\u627E\u5230\u8BE5\u9884\u8BBE\u3002",
  diagTitle: "\u5EFA\u8BAE\u68C0\u67E5",
  diagNone: "\u5F53\u524D\u914D\u7F6E\u6CA1\u6709\u9700\u8981\u63D0\u793A\u7684\u5730\u65B9\u3002",
  diagDeveloperRole: "{route}:baseURL \u770B\u8D77\u6765\u50CF\u65E7\u5F0F\u7F51\u5173,\u4F46 compat.supportsDeveloperRole \u5904\u4E8E\u5F00\u542F\u2014\u2014\u5EFA\u8BAE\u5B89\u5168\u7F51\u5173\u9884\u8BBE\u6216\u624B\u52A8\u5173\u95ED,\u907F\u514D 400 \u62A5\u9519\u3002",
  diagEmptyEffort: "{route} / {model}:reasoningEfforts.{level} \u4E3A\u7A7A(\u53EA\u6709 off \u53EF\u4EE5\u4E0D\u53D1\u9001)\u2014\u2014Host \u4F1A\u62D2\u7EDD\u8BE5\u5199\u5165\u3002",
  diagLooseEfforts: "{route} / {model}:\u58F0\u660E\u4E86 reasoningEfforts,\u4F46\u8BE5\u6A21\u578B\u6761\u76EE\u7684\u601D\u8003\u662F\u5173\u95ED\u7684(reasoningEfforts: false \u4F1A\u4FDD\u6301\u7981\u7528)\u3002",
  diagNoContext: "{route} / {model}:\u672A\u8BBE\u7F6E contextWindow\u2014\u2014DSH \u5C06\u56DE\u9000\u5230\u8DEF\u7531\u9ED8\u8BA4\u503C\u3002",
  diagNoModels: "{route}:\u672A\u58F0\u660E\u4EFB\u4F55\u6A21\u578B\u2014\u2014\u8DEF\u7531\u5C06\u4F7F\u7528\u5176\u5185\u7F6E\u76EE\u5F55\u3002",
  conflict: "\u53E6\u6709\u4FEE\u6539\u5148\u843D\u76D8(\u8BBE\u7F6E\u51B2\u7A81)\u3002\u9875\u9762\u5DF2\u91CD\u65B0\u52A0\u8F7D\u89C6\u56FE\u2014\u2014\u5982\u6709\u672A\u63D0\u4EA4\u8349\u7A3F\u8BF7\u91CD\u65B0\u5E94\u7528\u3002",
  writeFailed: "\u5199\u5165\u88AB\u62D2\u7EDD:",
  routeNotFound: "\u5728\u89E3\u6790\u540E\u7684\u8BBE\u7F6E\u4E2D\u627E\u4E0D\u5230\u8BE5\u8DEF\u7531\u3002",
  modelNotFound: "\u8BE5\u8DEF\u7531\u4E2D\u627E\u4E0D\u5230\u8BE5\u6A21\u578B\u3002",
  unknownError: "\u53D1\u751F\u610F\u5916\u9519\u8BEF\u3002",
  show: "\u663E\u793A",
  hide: "\u9690\u85CF",
  on: "\u5F00",
  off: "\u5173"
};

// src/client/constants.js
var THINKING_LEVELS = [
  "off",
  "minimal",
  "low",
  "medium",
  "high",
  "xhigh",
  "max"
];
var MODALITIES = ["text", "image"];
var THINKING_FORMATS = [
  "openai",
  "deepseek",
  "openrouter",
  "together",
  "zai",
  "qwen",
  "chat-template",
  "qwen-chat-template",
  "string-thinking",
  "ant-ling"
];
var MAX_TOKENS_FIELDS = ["max_completion_tokens", "max_tokens"];
var CACHE_CONTROL_FORMATS = ["anthropic"];
var APIS = ["openai-completions", "openai-responses", "anthropic-messages"];
var COMPAT_BOOLEAN_FIELDS = [
  "supportsDeveloperRole",
  "supportsReasoningEffort",
  "supportsStore",
  "supportsUsageInStreaming",
  "supportsTemperature",
  "supportsStrictMode",
  "supportsStrictTools",
  "supportsLongCacheRetention",
  "supportsEagerToolInputStreaming",
  "supportsCacheControlOnTools",
  "requiresToolResultName",
  "requiresAssistantAfterToolResult",
  "requiresThinkingAsText",
  "requiresReasoningContentOnAssistantMessages",
  "forceAdaptiveThinking",
  "allowEmptySignature"
];
var COMPAT_SELECT_FIELDS = [
  { key: "thinkingFormat", options: THINKING_FORMATS },
  { key: "maxTokensField", options: MAX_TOKENS_FIELDS },
  { key: "cacheControlFormat", options: CACHE_CONTROL_FORMATS }
];
var PROVIDER_NUMBER_FIELDS = [
  "timeoutMs",
  "websocketConnectTimeoutMs",
  "streamIdleTimeoutMs",
  "maxRequestImageBytes",
  "requestImagePixelBudget",
  "requestImageMaxBytes"
];
var NO_DEVELOPER_ROLE_HINTS = [
  "aliyun",
  "dashscope",
  "moonshot",
  "kimi",
  "zhipu",
  "bigmodel",
  "minimax",
  "volces",
  "ark",
  "siliconflow",
  "baidu",
  "qianfan",
  "maas"
];
function looksLikeLegacyGateway(baseURL = "") {
  const host = String(baseURL).toLowerCase();
  return NO_DEVELOPER_ROLE_HINTS.some((hint) => host.includes(hint));
}
function formatCapacity(value) {
  if (!Number.isInteger(value) || value <= 0) return "";
  if (value % 1e6 === 0) return `${String(value / 1e6)}M`;
  if (value % 1e3 === 0) return `${String(value / 1e3)}K`;
  return String(value);
}
function parseCapacity(text) {
  const trimmed = String(text).trim();
  if (trimmed === "") return void 0;
  const match = /^(\d+(?:\.\d+)?)\s*([km])?$/i.exec(trimmed);
  if (!match) return NaN;
  const value = Number(match[1]);
  const suffix = (match[2] || "").toLowerCase();
  if (suffix === "k") return Math.round(value * 1e3);
  if (suffix === "m") return Math.round(value * 1e6);
  return value;
}
function deepClone(value) {
  return JSON.parse(JSON.stringify(value));
}

// src/client/presets.js
function fullThinkingLevels() {
  return {
    off: null,
    minimal: "minimal",
    low: "low",
    medium: "medium",
    high: "high",
    xhigh: "xhigh",
    max: "max"
  };
}
function modelIndex(routeEntry, modelId) {
  const models = routeEntry?.models;
  if (!Array.isArray(models)) return -1;
  return models.findIndex((m) => m && m.id === modelId);
}
function routeBase(route) {
  return ["providers", route];
}
function modelOps(route, entry, build) {
  const models = Array.isArray(entry?.models) ? entry.models : [];
  const ops = [];
  for (const model of models) {
    if (!model || typeof model.id !== "string") continue;
    const index = modelIndex(entry, model.id);
    if (index < 0) continue;
    build(ops, [...routeBase(route), "models", index], model);
  }
  return ops;
}
var BUILTIN_PRESETS = [
  {
    id: "safe-gateway",
    nameKey: "builtinSafeGateway",
    descKey: "builtinSafeGatewayDesc",
    buildOps(route, entry) {
      const base = routeBase(route);
      return [
        { op: "set", path: [...base, "compat", "supportsDeveloperRole"], value: false },
        { op: "set", path: [...base, "compat", "supportsReasoningEffort"], value: true }
      ];
    }
  },
  {
    id: "openai-native",
    nameKey: "builtinOpenaiNative",
    descKey: "builtinOpenaiNativeDesc",
    buildOps(route, entry) {
      const base = routeBase(route);
      return [
        { op: "set", path: [...base, "compat", "supportsDeveloperRole"], value: true },
        { op: "set", path: [...base, "compat", "supportsReasoningEffort"], value: true },
        { op: "set", path: [...base, "compat", "thinkingFormat"], value: "openai" },
        { op: "set", path: [...base, "compat", "maxTokensField"], value: "max_completion_tokens" }
      ];
    }
  },
  {
    id: "deepseek-dialect",
    nameKey: "builtinDeepseekDialect",
    descKey: "builtinDeepseekDialectDesc",
    buildOps(route, entry) {
      const base = routeBase(route);
      return [
        { op: "set", path: [...base, "compat", "thinkingFormat"], value: "deepseek" },
        { op: "set", path: [...base, "compat", "supportsDeveloperRole"], value: true },
        { op: "set", path: [...base, "compat", "supportsReasoningEffort"], value: true }
      ];
    }
  },
  {
    id: "qwen-dialect",
    nameKey: "builtinQwenDialect",
    descKey: "builtinQwenDialectDesc",
    buildOps(route, entry) {
      const base = routeBase(route);
      return [
        { op: "set", path: [...base, "compat", "thinkingFormat"], value: "qwen" },
        { op: "set", path: [...base, "compat", "supportsDeveloperRole"], value: false },
        { op: "set", path: [...base, "compat", "supportsReasoningEffort"], value: true }
      ];
    }
  },
  {
    id: "max-thinking",
    nameKey: "builtinMaxThinking",
    descKey: "builtinMaxThinkingDesc",
    buildOps(route, entry) {
      const base = routeBase(route);
      const levels = fullThinkingLevels();
      return [
        ...modelOps(route, entry, (ops, modelPath) => {
          ops.push({ op: "set", path: [...modelPath, "reasoningEfforts"], value: levels });
        }),
        { op: "set", path: [...base, "reasoning"], value: "high" },
        {
          op: "set",
          path: [...base, "thinkingBudgets"],
          value: { minimal: 256, low: 1024, medium: 4096, high: 16384 }
        }
      ];
    }
  },
  {
    id: "text-only",
    nameKey: "builtinTextOnly",
    descKey: "builtinTextOnlyDesc",
    buildOps(route, entry) {
      const base = routeBase(route);
      return [
        { op: "set", path: [...base, "defaultInput"], value: ["text"] },
        ...modelOps(route, entry, (ops, modelPath) => {
          ops.push({ op: "set", path: [...modelPath, "input"], value: ["text"] });
        })
      ];
    }
  },
  {
    id: "image-ready",
    nameKey: "builtinImageReady",
    descKey: "builtinImageReadyDesc",
    buildOps(route, entry) {
      const base = routeBase(route);
      return [
        { op: "set", path: [...base, "defaultInput"], value: ["text", "image"] },
        ...modelOps(route, entry, (ops, modelPath) => {
          ops.push({ op: "set", path: [...modelPath, "input"], value: ["text", "image"] });
        })
      ];
    }
  }
];

// src/client/store.js
var NS = "llm-pi-ai";
var SELF_NS = "model-capability";
var LANGUAGE_FIELD = "language";
var CUSTOM_PRESETS_FIELD = "customPresets";
var CapabilityStore = class {
  constructor({ api, llmScope, selfScope, locale }) {
    this.api = api;
    this.llmScope = llmScope;
    this.selfScope = selfScope;
    this.locale = locale;
    this.materialized = /* @__PURE__ */ new Set();
  }
  // ——— read faces ———
  llmSnapshot() {
    return this.llmScope.getSnapshot();
  }
  selfSnapshot() {
    return this.selfScope.getSnapshot();
  }
  providers() {
    const value = this.llmSnapshot().value;
    if (!value || typeof value !== "object" || Array.isArray(value)) return {};
    return value.providers && typeof value.providers === "object" ? value.providers : {};
  }
  userProviders() {
    const user = this.llmSnapshot().user;
    if (!user || typeof user !== "object" || Array.isArray(user)) return {};
    return user.providers && typeof user.providers === "object" ? user.providers : {};
  }
  routeNames() {
    return Object.keys(this.providers());
  }
  route(route) {
    return this.providers()[route];
  }
  modelsOf(route) {
    const models = this.route(route)?.models;
    return Array.isArray(models) ? models : [];
  }
  modelIndexById(route, modelId) {
    return this.modelsOf(route).findIndex((m) => m && m.id === modelId);
  }
  /** Effective UI language: own preference, else the DSH locale. */
  effectiveLanguage() {
    const self = this.selfSnapshot().value;
    const pref = self && typeof self === "object" && self.language !== void 0 ? self.language : "follow";
    if (pref === "follow") {
      const active = this.locale?.getSnapshot?.().active;
      return active === "zh" ? "zh" : "en";
    }
    return pref === "zh" ? "zh" : "en";
  }
  writable() {
    return this.llmSnapshot().writable === true;
  }
  mode() {
    return this.llmSnapshot().mode;
  }
  // ——— low-level writes ———
  async writeOps(ops) {
    const snap = this.llmSnapshot();
    const result = await this.api.settings.mutate({
      ns: NS,
      ops,
      ...snap.revision === void 0 ? {} : { expectedRevision: snap.revision }
    });
    if (!result.result.ok) {
      return { ok: false, code: result.result.error?.code, message: result.result.error?.message };
    }
    return { ok: true, revision: result.result.value.revision };
  }
  async writePath(path, value) {
    return this.writeOps([{ op: "set", path, value }]);
  }
  async unsetPath(path) {
    return this.writeOps([{ op: "unset", path }]);
  }
  // ——— materialization ———
  /** Make sure the route exists in the USER layer before nested writes. */
  async ensureRouteMaterialized(route) {
    if (this.materialized.has(route)) return { ok: true };
    const snap = this.llmSnapshot();
    const user = snap.user;
    if (user && typeof user === "object" && user.providers && user.providers[route] !== void 0) {
      this.materialized.add(route);
      return { ok: true };
    }
    const effective = snap.value?.providers?.[route];
    if (effective === void 0) return { ok: false, message: "route-not-found" };
    const copy = deepClone(effective);
    const result = await this.writeOps([
      { op: "set", path: ["providers", route], value: copy }
    ]);
    if (result.ok) this.materialized.add(route);
    return result;
  }
  // ——— field writers used by the UI ———
  /** Materialize first (if needed), then run the ops on one route. */
  async writeRouteField(route, suffixPath, value, { unset = false } = {}) {
    const materialized = await this.ensureRouteMaterialized(route);
    if (!materialized.ok) return materialized;
    const path = ["providers", route, ...suffixPath];
    return unset ? this.unsetPath(path) : this.writePath(path, value);
  }
  async writeModelField(route, modelId, fields) {
    const materialized = await this.ensureRouteMaterialized(route);
    if (!materialized.ok) return materialized;
    const index = this.modelIndexById(route, modelId);
    if (index < 0) return { ok: false, message: "model-not-found" };
    const ops = [];
    for (const [field, value] of Object.entries(fields)) {
      const path = ["providers", route, "models", index, field];
      if (value === UNSET) ops.push({ op: "unset", path });
      else ops.push({ op: "set", path, value });
    }
    if (ops.length === 0) return { ok: true };
    return this.writeOps(ops);
  }
  /** Copy one model's visible settings to every model of the same route. */
  async applyModelToAll(route, modelId, fieldNames) {
    const source = this.modelsOf(route).find((m) => m && m.id === modelId);
    if (!source) return { ok: false, message: "model-not-found" };
    const materialized = await this.ensureRouteMaterialized(route);
    if (!materialized.ok) return materialized;
    const ops = [];
    for (const model of this.modelsOf(route)) {
      if (!model || model.id === modelId) continue;
      const index = this.modelIndexById(route, model.id);
      if (index < 0) continue;
      for (const field of fieldNames) {
        if (!(field in source)) continue;
        ops.push({
          op: "set",
          path: ["providers", route, "models", index, field],
          value: deepClone(source[field])
        });
      }
    }
    if (ops.length === 0) return { ok: true };
    return this.writeOps(ops);
  }
  // ——— presets ———
  builtinPresets() {
    return BUILTIN_PRESETS;
  }
  /** Apply a built-in preset to the selected routes in one atomic write. */
  async applyBuiltinPreset(presetId, routeIds) {
    const preset = BUILTIN_PRESETS.find((p) => p.id === presetId);
    if (!preset) return { ok: false, message: "preset-not-found" };
    const providers = this.providers();
    const routes = routeIds.filter((r) => providers[r] !== void 0);
    if (routes.length === 0) return { ok: false, message: "route-not-found" };
    const ops = [];
    for (const route of routes) {
      ops.push(...preset.buildOps(route, providers[route]));
    }
    for (const route of routes) {
      const materialized = await this.ensureRouteMaterialized(route);
      if (!materialized.ok) return materialized;
    }
    return this.writeOps(ops);
  }
  customPresets() {
    const self = this.selfSnapshot().value;
    if (!self || typeof self !== "object") return [];
    return Array.isArray(self.customPresets) ? self.customPresets : [];
  }
  /** Save the current user providers as a custom preset. */
  async saveCustomPreset(name) {
    const providers = this.userProviders();
    if (Object.keys(providers).length === 0) {
      return { ok: false, message: "no-user-routes" };
    }
    const id = `cp_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
    const item = {
      id,
      name: String(name || "preset").trim(),
      createdAt: (/* @__PURE__ */ new Date()).toISOString(),
      payload: JSON.stringify({ providers })
    };
    const next = [...this.customPresets(), item];
    const snap = this.selfSnapshot();
    const result = await this.api.settings.mutate({
      ns: SELF_NS,
      ops: [{ op: "set", path: [CUSTOM_PRESETS_FIELD], value: next }],
      ...snap.revision === void 0 ? {} : { expectedRevision: snap.revision }
    });
    return result.result.ok ? { ok: true } : { ok: false, code: result.result.error?.code, message: result.result.error?.message };
  }
  async deleteCustomPreset(id) {
    const next = this.customPresets().filter((p) => p.id !== id);
    const snap = this.selfSnapshot();
    const result = await this.api.settings.mutate({
      ns: SELF_NS,
      ops: [{ op: "set", path: [CUSTOM_PRESETS_FIELD], value: next }],
      ...snap.revision === void 0 ? {} : { expectedRevision: snap.revision }
    });
    return result.result.ok ? { ok: true } : { ok: false, code: result.result.error?.code, message: result.result.error?.message };
  }
  /** Apply a custom preset: replaces the whole llm-pi-ai user section. */
  async applyCustomPreset(id) {
    const preset = this.customPresets().find((p) => p.id === id);
    if (!preset) return { ok: false, message: "preset-not-found" };
    let parsed;
    try {
      parsed = JSON.parse(preset.payload);
    } catch {
      return { ok: false, message: "preset-corrupt" };
    }
    const section = parsed && typeof parsed === "object" && parsed.providers ? parsed : { providers: parsed };
    const snap = this.llmSnapshot();
    const result = await this.api.settings.replace({
      ns: NS,
      section,
      ...snap.revision === void 0 ? {} : { expectedRevision: snap.revision }
    });
    if (result.result.ok) {
      this.materialized.clear();
      return { ok: true };
    }
    return { ok: false, code: result.result.error?.code, message: result.result.error?.message };
  }
  // ——— self namespace (language) ———
  /** Persist the page language preference. */
  async setLanguage(value) {
    const snap = this.selfSnapshot();
    const result = await this.api.settings.mutate({
      ns: SELF_NS,
      ops: [{ op: "set", path: [LANGUAGE_FIELD], value }],
      ...snap.revision === void 0 ? {} : { expectedRevision: snap.revision }
    });
    return result.result.ok ? { ok: true } : { ok: false, code: result.result.error?.code, message: result.result.error?.message };
  }
};
var UNSET = Symbol("unset");

// src/client/components/Section.jsx
var import_react5 = require("react");

// src/client/components/ui.jsx
var import_react = require("react");
var import_jsx_runtime = require("react/jsx-runtime");
var border = "1px solid color-mix(in srgb, currentColor 22%, transparent)";
var borderStrong = "1px solid color-mix(in srgb, currentColor 45%, transparent)";
var inputStyle = {
  font: "inherit",
  color: "inherit",
  background: "transparent",
  border,
  borderRadius: 6,
  padding: "4px 8px",
  outline: "none",
  minWidth: 0,
  width: "100%",
  boxSizing: "border-box"
};
function Btn({ children, onClick, disabled, title, kind = "default", style }) {
  const base = {
    font: "inherit",
    color: "inherit",
    background: "transparent",
    border,
    borderRadius: 6,
    padding: "4px 10px",
    cursor: disabled ? "not-allowed" : "pointer",
    opacity: disabled ? 0.5 : 1
  };
  const kinds = {
    default: {},
    primary: {
      border: borderStrong,
      background: "color-mix(in srgb, currentColor 10%, transparent)"
    },
    danger: {
      border,
      color: "color-mix(in srgb, #dc2626 80%, currentColor)"
    }
  };
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
    "button",
    {
      type: "button",
      title,
      disabled,
      onClick,
      style: { ...base, ...kinds[kind], ...style },
      children
    }
  );
}
function Field({ label, hint, children, style }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("label", { style: { display: "flex", flexDirection: "column", gap: 4, minWidth: 0, ...style }, children: [
    /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { style: { fontSize: 12, opacity: 0.75 }, children: label }),
    children,
    hint ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { style: { fontSize: 11, opacity: 0.55 }, children: hint }) : null
  ] });
}
function TextInput({ value, onCommit, placeholder, disabled, style, width }) {
  const [draft, setDraft] = (0, import_react.useState)(String(value ?? ""));
  (0, import_react.useEffect)(() => {
    setDraft(String(value ?? ""));
  }, [value]);
  const commit = () => {
    if (draft !== String(value ?? "") && typeof onCommit === "function") onCommit(draft);
  };
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
    "input",
    {
      value: draft,
      disabled,
      placeholder,
      onChange: (e) => setDraft(e.target.value),
      onBlur: commit,
      onKeyDown: (e) => {
        if (e.key === "Enter") e.currentTarget.blur();
      },
      style: { ...inputStyle, width: width ?? "100%", ...style }
    }
  );
}
function CapacityInput({ value, onCommit, placeholder, disabled, hint, style }) {
  const [draft, setDraft] = (0, import_react.useState)(() => formatCapacity(value));
  const [bad, setBad] = (0, import_react.useState)(false);
  (0, import_react.useEffect)(() => {
    if (!bad) setDraft(formatCapacity(value));
  }, [value, bad]);
  const commit = () => {
    const trimmed = draft.trim();
    if (trimmed === "") {
      if (value !== void 0 && value !== null && typeof onCommit === "function") onCommit(null);
      return;
    }
    const parsed = parseCapacity(trimmed);
    if (Number.isNaN(parsed)) {
      setBad(true);
      setDraft(formatCapacity(value));
      setTimeout(() => setBad(false), 900);
      return;
    }
    if (parsed !== value && typeof onCommit === "function") onCommit(parsed);
  };
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { style: { display: "flex", flexDirection: "column", gap: 2, width: "100%", ...style }, children: [
    /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
      "input",
      {
        value: draft,
        disabled,
        placeholder: placeholder ?? hint,
        onChange: (e) => setDraft(e.target.value),
        onBlur: commit,
        onKeyDown: (e) => {
          if (e.key === "Enter") e.currentTarget.blur();
        },
        style: {
          ...inputStyle,
          borderColor: bad ? "color-mix(in srgb, #dc2626 70%, currentColor)" : void 0
        }
      }
    ),
    hint ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { style: { fontSize: 11, opacity: 0.55 }, children: hint }) : null
  ] });
}
function NumberInput({ value, onCommit, placeholder, disabled, style }) {
  const [draft, setDraft] = (0, import_react.useState)(value === void 0 || value === null ? "" : String(value));
  (0, import_react.useEffect)(() => {
    setDraft(value === void 0 || value === null ? "" : String(value));
  }, [value]);
  const commit = () => {
    const trimmed = draft.trim();
    if (trimmed === "") {
      if (value !== void 0 && value !== null && typeof onCommit === "function") onCommit(null);
      return;
    }
    const parsed = Number(trimmed);
    if (!Number.isFinite(parsed)) {
      setDraft(value === void 0 || value === null ? "" : String(value));
      return;
    }
    if (parsed !== value && typeof onCommit === "function") onCommit(parsed);
  };
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
    "input",
    {
      value: draft,
      disabled,
      placeholder,
      onChange: (e) => setDraft(e.target.value),
      onBlur: commit,
      onKeyDown: (e) => {
        if (e.key === "Enter") e.currentTarget.blur();
      },
      style: { ...inputStyle, ...style }
    }
  );
}
function Select({ value, options, onChange, allowUnset, unsetLabel, disabled, style }) {
  const present = value !== void 0 && value !== null;
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)(
    "select",
    {
      value: present ? String(value) : "",
      disabled,
      onChange: (e) => {
        const text = e.target.value;
        if (text === "__unset__") onChange(void 0);
        else onChange(text);
      },
      style: { ...inputStyle, cursor: "pointer", ...style },
      children: [
        !present && allowUnset ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)("option", { value: "", children: unsetLabel }) : null,
        present && allowUnset ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)("option", { value: "__unset__", children: unsetLabel }) : null,
        !present && !allowUnset ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)("option", { value: "", children: "\u2014" }) : null,
        options.map((option) => {
          const label = typeof option === "string" ? option : option.label;
          const value_ = typeof option === "string" ? option : option.value;
          return /* @__PURE__ */ (0, import_jsx_runtime.jsx)("option", { value: String(value_), children: label }, value_);
        })
      ]
    }
  );
}
function Check({ label, checked, onChange, disabled, hint }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("label", { style: { display: "flex", gap: 8, alignItems: "flex-start", cursor: disabled ? "not-allowed" : "pointer", opacity: disabled ? 0.55 : 1 }, children: [
    /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
      "input",
      {
        type: "checkbox",
        checked: checked === true,
        disabled,
        onChange: (e) => typeof onChange === "function" && onChange(e.target.checked),
        style: { marginTop: 3, accentColor: "currentColor" }
      }
    ),
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("span", { style: { display: "flex", flexDirection: "column", gap: 2 }, children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { children: label }),
      hint ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { style: { fontSize: 11, opacity: 0.55 }, children: hint }) : null
    ] })
  ] });
}
function Fold({ title, badge, defaultOpen = false, children, right }) {
  const [open, setOpen] = (0, import_react.useState)(defaultOpen);
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { style: { border, borderRadius: 8, overflow: "hidden" }, children: [
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)(
      "div",
      {
        role: "button",
        tabIndex: 0,
        onClick: () => setOpen(!open),
        onKeyDown: (e) => {
          if (e.key === "Enter" || e.key === " ") {
            e.preventDefault();
            setOpen(!open);
          }
        },
        style: {
          display: "flex",
          alignItems: "center",
          gap: 8,
          padding: "8px 12px",
          cursor: "pointer",
          userSelect: "none",
          background: "color-mix(in srgb, currentColor 5%, transparent)"
        },
        children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { style: { fontSize: 12, opacity: 0.7, width: 14, display: "inline-block" }, children: open ? "\u25BE" : "\u25B8" }),
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { style: { fontWeight: 600 }, children: title }),
          badge ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)(Badge, { tone: "neutral", children: badge }) : null,
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { style: { flex: 1 } }),
          right
        ]
      }
    ),
    open ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { style: { padding: 12 }, children }) : null
  ] });
}
var badgeTones = {
  neutral: {},
  good: { color: "color-mix(in srgb, #16a34a 80%, currentColor)" },
  warn: { color: "color-mix(in srgb, #d97706 85%, currentColor)" },
  bad: { color: "color-mix(in srgb, #dc2626 80%, currentColor)" }
};
function Badge({ children, tone = "neutral" }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
    "span",
    {
      style: {
        fontSize: 11,
        padding: "1px 7px",
        borderRadius: 999,
        border,
        opacity: 0.9,
        whiteSpace: "nowrap",
        ...badgeTones[tone]
      },
      children
    }
  );
}
function WarningBox({ children, tone = "warn" }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)(
    "div",
    {
      style: {
        display: "flex",
        gap: 8,
        alignItems: "flex-start",
        border,
        borderRadius: 8,
        padding: "8px 12px",
        fontSize: 13,
        ...tone === "warn" ? { borderColor: "color-mix(in srgb, #d97706 45%, transparent)" } : tone === "bad" ? { borderColor: "color-mix(in srgb, #dc2626 50%, transparent)" } : {}
      },
      children: [
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { style: { opacity: 0.8 }, children: tone === "bad" ? "\u2715" : tone === "good" ? "\u2713" : "\u2139" }),
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { children })
      ]
    }
  );
}
function Grid({ columns = 2, gap = 12, children, style }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
    "div",
    {
      style: {
        display: "grid",
        gridTemplateColumns: `repeat(${columns}, minmax(0, 1fr))`,
        gap,
        ...style
      },
      children
    }
  );
}
function Modal({ title, children, onClose }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
    "div",
    {
      style: {
        position: "fixed",
        inset: 0,
        zIndex: 1e3,
        background: "rgba(0,0,0,0.35)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        padding: 24
      },
      onClick: onClose,
      children: /* @__PURE__ */ (0, import_jsx_runtime.jsxs)(
        "div",
        {
          role: "dialog",
          "aria-modal": "true",
          onClick: (e) => e.stopPropagation(),
          style: {
            background: "Canvas",
            color: "CanvasText",
            border,
            borderRadius: 12,
            padding: 16,
            maxWidth: 540,
            width: "100%",
            maxHeight: "80vh",
            overflow: "auto",
            boxShadow: "0 12px 40px rgba(0,0,0,0.25)"
          },
          children: [
            /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { style: { display: "flex", alignItems: "center", gap: 8, marginBottom: 12 }, children: [
              /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { style: { fontWeight: 700, flex: 1 }, children: title }),
              /* @__PURE__ */ (0, import_jsx_runtime.jsx)(Btn, { onClick: onClose, title: "close", style: { padding: "2px 8px" }, children: "\u2715" })
            ] }),
            children
          ]
        }
      )
    }
  );
}
function Toast({ toast }) {
  if (!toast) return null;
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
    "div",
    {
      style: {
        border,
        borderRadius: 8,
        padding: "8px 12px",
        fontSize: 13,
        ...toast.tone === "bad" ? { borderColor: "color-mix(in srgb, #dc2626 50%, transparent)" } : toast.tone === "good" ? { borderColor: "color-mix(in srgb, #16a34a 50%, transparent)" } : {}
      },
      children: toast.text
    }
  );
}

// src/client/components/PresetBar.jsx
var import_react2 = require("react");
var import_jsx_runtime2 = require("react/jsx-runtime");
function PresetBar({ store, t, routes, onToast, disabled }) {
  const [dialog, setDialog] = (0, import_react2.useState)(null);
  const [selected, setSelected] = (0, import_react2.useState)(null);
  const [saving, setSaving] = (0, import_react2.useState)(false);
  const [presetName, setPresetName] = (0, import_react2.useState)("");
  const builtins = store.builtinPresets();
  const customs = store.customPresets();
  const openDialog = (preset) => {
    const all = {};
    for (const route of routes) all[route] = true;
    setSelected(all);
    setDialog(preset);
  };
  const apply2 = async () => {
    const routeIds = Object.keys(selected ?? {}).filter((r) => selected[r]);
    const result = await store.applyBuiltinPreset(dialog.presetId, routeIds);
    onToast?.(
      result.ok ? { tone: "good", text: t("presetApplied") } : { tone: "bad", text: `${t("presetFailed")} ${result.message ?? t("unknownError")}` }
    );
    setDialog(null);
  };
  const save = async () => {
    setSaving(true);
    const name = presetName.trim();
    const result = await store.saveCustomPreset(name || t("savePresetName"));
    setSaving(false);
    onToast?.(
      result.ok ? { tone: "good", text: t("presetSaved") } : {
        tone: "bad",
        text: result.message === "no-user-routes" ? t("noUserRoutesHint") : `${t("presetFailed")} ${result.message ?? t("unknownError")}`
      }
    );
    if (result.ok) setPresetName("");
  };
  const applyCustom = async (id) => {
    if (!window.confirm(t("confirmApplyCustom"))) return;
    const result = await store.applyCustomPreset(id);
    onToast?.(
      result.ok ? { tone: "good", text: t("presetApplied") } : { tone: "bad", text: `${t("presetFailed")} ${result.message ?? t("unknownError")}` }
    );
  };
  const deleteCustom = async (id) => {
    if (!window.confirm(t("confirmDeleteCustom"))) return;
    const result = await store.deleteCustomPreset(id);
    onToast?.(
      result.ok ? { tone: "good", text: t("presetSaved") } : { tone: "bad", text: `${t("presetFailed")} ${result.message ?? t("unknownError")}` }
    );
  };
  return /* @__PURE__ */ (0, import_jsx_runtime2.jsxs)("div", { style: { display: "flex", flexDirection: "column", gap: 10 }, children: [
    /* @__PURE__ */ (0, import_jsx_runtime2.jsx)("div", { style: { fontSize: 13, fontWeight: 600 }, children: t("presetTitle") }),
    /* @__PURE__ */ (0, import_jsx_runtime2.jsx)("div", { style: { fontSize: 12, opacity: 0.7 }, children: t("presetIntro") }),
    /* @__PURE__ */ (0, import_jsx_runtime2.jsx)("div", { style: { display: "flex", flexWrap: "wrap", gap: 8 }, children: builtins.map((preset) => /* @__PURE__ */ (0, import_jsx_runtime2.jsxs)(
      "button",
      {
        type: "button",
        disabled: disabled || routes.length === 0,
        onClick: () => openDialog(preset),
        title: t(preset.descKey),
        style: {
          display: "flex",
          flexDirection: "column",
          gap: 2,
          textAlign: "left",
          font: "inherit",
          color: "inherit",
          background: "transparent",
          border: "1px solid color-mix(in srgb, currentColor 22%, transparent)",
          borderRadius: 8,
          padding: "8px 12px",
          cursor: "pointer",
          maxWidth: 220,
          opacity: disabled || routes.length === 0 ? 0.5 : 1
        },
        children: [
          /* @__PURE__ */ (0, import_jsx_runtime2.jsx)("span", { style: { fontWeight: 600, fontSize: 13 }, children: t(preset.nameKey) }),
          /* @__PURE__ */ (0, import_jsx_runtime2.jsx)("span", { style: { fontSize: 11, opacity: 0.65 }, children: t(preset.descKey) })
        ]
      },
      preset.id
    )) }),
    /* @__PURE__ */ (0, import_jsx_runtime2.jsx)("div", { style: { display: "flex", gap: 8, alignItems: "flex-start", flexWrap: "wrap" }, children: /* @__PURE__ */ (0, import_jsx_runtime2.jsx)(Field, { label: t("savePreset"), style: { flex: 1, minWidth: 220 }, children: /* @__PURE__ */ (0, import_jsx_runtime2.jsxs)("div", { style: { display: "flex", gap: 8 }, children: [
      /* @__PURE__ */ (0, import_jsx_runtime2.jsx)(
        TextInput,
        {
          value: presetName,
          placeholder: t("savePresetName"),
          disabled: disabled || saving,
          onCommit: () => save()
        }
      ),
      /* @__PURE__ */ (0, import_jsx_runtime2.jsx)(Btn, { kind: "primary", disabled: disabled || saving, onClick: save, children: t("savePresetBtn") })
    ] }) }) }),
    Object.keys(store.userProviders()).length === 0 ? /* @__PURE__ */ (0, import_jsx_runtime2.jsx)(WarningBox, { tone: "neutral", children: t("noUserRoutesHint") }) : null,
    customs.length > 0 ? /* @__PURE__ */ (0, import_jsx_runtime2.jsxs)("div", { style: { display: "flex", flexDirection: "column", gap: 6 }, children: [
      /* @__PURE__ */ (0, import_jsx_runtime2.jsx)("div", { style: { fontSize: 12, opacity: 0.7, fontWeight: 600 }, children: t("customPresetsTitle") }),
      customs.map((preset) => /* @__PURE__ */ (0, import_jsx_runtime2.jsxs)(
        "div",
        {
          style: {
            display: "flex",
            alignItems: "center",
            gap: 8,
            border: "1px solid color-mix(in srgb, currentColor 22%, transparent)",
            borderRadius: 8,
            padding: "6px 10px"
          },
          children: [
            /* @__PURE__ */ (0, import_jsx_runtime2.jsx)("span", { style: { flex: 1, fontWeight: 600, fontSize: 13 }, children: preset.name || preset.id }),
            /* @__PURE__ */ (0, import_jsx_runtime2.jsx)("span", { style: { fontSize: 11, opacity: 0.55 }, children: new Date(preset.createdAt).toLocaleString() }),
            /* @__PURE__ */ (0, import_jsx_runtime2.jsx)(Btn, { disabled, onClick: () => applyCustom(preset.id), title: t("applyCustom"), children: t("applyPreset") }),
            /* @__PURE__ */ (0, import_jsx_runtime2.jsx)(Btn, { kind: "danger", disabled, onClick: () => deleteCustom(preset.id), children: "\u2715" })
          ]
        },
        preset.id
      ))
    ] }) : null,
    dialog ? /* @__PURE__ */ (0, import_jsx_runtime2.jsxs)(Modal, { title: `${t(dialog.nameKey)} \u2014 ${t("presetRoutes")}`, onClose: () => setDialog(null), children: [
      /* @__PURE__ */ (0, import_jsx_runtime2.jsx)(
        "div",
        {
          style: {
            display: "flex",
            flexDirection: "column",
            gap: 8,
            maxHeight: 320,
            overflow: "auto",
            marginBottom: 12
          },
          children: routes.map((route) => /* @__PURE__ */ (0, import_jsx_runtime2.jsx)(
            Check,
            {
              label: route,
              checked: selected?.[route] === true,
              onChange: (checked) => setSelected({ ...selected, [route]: checked })
            },
            route
          ))
        }
      ),
      /* @__PURE__ */ (0, import_jsx_runtime2.jsxs)("div", { style: { display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap" }, children: [
        /* @__PURE__ */ (0, import_jsx_runtime2.jsx)(
          Btn,
          {
            onClick: () => {
              const all = {};
              for (const route of routes) all[route] = true;
              setSelected(all);
            },
            children: t("selectAll")
          }
        ),
        /* @__PURE__ */ (0, import_jsx_runtime2.jsx)(Btn, { onClick: () => setSelected({}), children: t("deselectAll") }),
        /* @__PURE__ */ (0, import_jsx_runtime2.jsx)("span", { style: { flex: 1 } }),
        /* @__PURE__ */ (0, import_jsx_runtime2.jsx)(Btn, { onClick: () => setDialog(null), children: t("cancel") }),
        /* @__PURE__ */ (0, import_jsx_runtime2.jsx)(Btn, { kind: "primary", onClick: apply2, children: t("applyPreset") })
      ] })
    ] }) : null
  ] });
}

// src/client/components/DefaultsEditor.jsx
var import_jsx_runtime3 = require("react/jsx-runtime");
function DefaultsEditor({ store, t, route, entry, onToast, disabled }) {
  const toast = (result) => onToast?.(
    result.ok ? { tone: "good", text: t("applied") } : { tone: "bad", text: `${t("writeFailed")} ${result.message ?? t("unknownError")}` }
  );
  const write = async (suffix, value) => {
    const result = await store.writeRouteField(route, suffix, value);
    toast(result);
  };
  const unset = async (suffix) => {
    const result = await store.writeRouteField(route, suffix, void 0, { unset: true });
    toast(result);
  };
  const setCapacity = (suffix, parsedOrNull) => {
    if (parsedOrNull === null) unset(suffix);
    else write(suffix, parsedOrNull);
  };
  const setPlain = (suffix, parsedOrNull) => {
    if (parsedOrNull === null) unset(suffix);
    else write(suffix, parsedOrNull);
  };
  const toggleDefaultInput = (modality, checked) => {
    const current = Array.isArray(entry.defaultInput) ? entry.defaultInput : [];
    const next = checked ? [...current, modality] : current.filter((m) => m !== modality);
    write(["defaultInput"], next);
  };
  const budgets = entry.thinkingBudgets ?? {};
  const setBudget = (key, parsedOrNull) => {
    const next = { ...budgets };
    if (parsedOrNull === null) delete next[key];
    else next[key] = parsedOrNull;
    if (Object.keys(next).length === 0) unset(["thinkingBudgets"]);
    else write(["thinkingBudgets"], next);
  };
  return /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)("div", { style: { display: "flex", flexDirection: "column", gap: 12 }, children: [
    /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(Grid, { columns: 3, children: [
      /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Field, { label: t("defaultContextWindow"), hint: t("capacityHint"), children: /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
        CapacityInput,
        {
          value: entry.defaultContextWindow,
          onCommit: (parsed) => setCapacity(["defaultContextWindow"], parsed),
          disabled
        }
      ) }),
      /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Field, { label: t("defaultMaxTokens"), hint: t("capacityHint"), children: /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
        CapacityInput,
        {
          value: entry.defaultMaxTokens,
          onCommit: (parsed) => setCapacity(["defaultMaxTokens"], parsed),
          disabled
        }
      ) }),
      /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Field, { label: t("reasoningDefault"), children: /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
        Select,
        {
          value: entry.reasoning,
          options: THINKING_LEVELS,
          allowUnset: true,
          unsetLabel: "\u2014",
          disabled,
          onChange: (value) => value === void 0 ? unset(["reasoning"]) : write(["reasoning"], value)
        }
      ) })
    ] }),
    /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(Grid, { columns: 2, children: [
      /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Field, { label: t("defaultInput"), children: /* @__PURE__ */ (0, import_jsx_runtime3.jsx)("div", { style: { display: "flex", gap: 16 }, children: MODALITIES.map((modality) => /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
        Check,
        {
          label: t(modality === "text" ? "modalityText" : "modalityImage"),
          checked: Array.isArray(entry.defaultInput) && entry.defaultInput.includes(modality),
          disabled,
          onChange: (checked) => toggleDefaultInput(modality, checked)
        },
        modality
      )) }) }),
      /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Field, { label: t("thinkingBudgets"), children: /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Grid, { columns: 4, gap: 8, children: ["minimal", "low", "medium", "high"].map((key) => /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Field, { label: key, children: /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
        NumberInput,
        {
          value: budgets[key],
          disabled,
          onCommit: (parsed) => setBudget(key, parsed)
        }
      ) }, key)) }) })
    ] }),
    /* @__PURE__ */ (0, import_jsx_runtime3.jsxs)(Grid, { columns: 2, children: [
      /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Field, { label: t("cacheRetention"), children: /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
        Select,
        {
          value: entry.cacheRetention,
          options: ["none", "short", "long"],
          allowUnset: true,
          unsetLabel: "\u2014",
          disabled,
          onChange: (value) => value === void 0 ? unset(["cacheRetention"]) : write(["cacheRetention"], value)
        }
      ) }),
      /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(Field, { label: t("transport"), children: /* @__PURE__ */ (0, import_jsx_runtime3.jsx)(
        Select,
        {
          value: entry.transport,
          options: ["sse", "websocket", "websocket-cached", "auto"],
          allowUnset: true,
          unsetLabel: "\u2014",
          disabled,
          onChange: (value) => value === void 0 ? unset(["transport"]) : write(["transport"], value)
        }
      ) })
    ] })
  ] });
}

// src/client/components/CompatEditor.jsx
var import_jsx_runtime4 = require("react/jsx-runtime");
function CompatEditor({ store, t, route, suffixPath, compat, onToast, disabled }) {
  const bool = (field) => compat?.[field] === true;
  const setBool = async (field, value) => {
    const result = await store.writeRouteField(route, [...suffixPath, "compat", field], value);
    onToast?.(
      result.ok ? { tone: "good", text: t("applied") } : { tone: "bad", text: `${t("writeFailed")} ${result.message ?? t("unknownError")}` }
    );
  };
  const selectValue = (field) => compat?.[field];
  const setSelect = async (field, value) => {
    if (value === void 0) {
      const result2 = await store.writeRouteField(route, [...suffixPath, "compat", field], void 0, { unset: true });
      onToast?.(
        result2.ok ? { tone: "good", text: t("applied") } : { tone: "bad", text: `${t("writeFailed")} ${result2.message ?? t("unknownError")}` }
      );
      return;
    }
    const result = await store.writeRouteField(route, [...suffixPath, "compat", field], value);
    onToast?.(
      result.ok ? { tone: "good", text: t("applied") } : { tone: "bad", text: `${t("writeFailed")} ${result.message ?? t("unknownError")}` }
    );
  };
  return /* @__PURE__ */ (0, import_jsx_runtime4.jsxs)("div", { style: { display: "flex", flexDirection: "column", gap: 10 }, children: [
    /* @__PURE__ */ (0, import_jsx_runtime4.jsx)("div", { style: { fontSize: 12, opacity: 0.7 }, children: t("compatIntro") }),
    /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(Grid, { columns: 2, children: COMPAT_BOOLEAN_FIELDS.map((field) => {
      const hintKey = `${field}Hint`;
      return /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(
        Check,
        {
          label: t(field) ?? field,
          hint: hintKey in en ? t(hintKey) : void 0,
          checked: bool(field),
          disabled,
          onChange: (value) => setBool(field, value)
        },
        field
      );
    }) }),
    /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(Grid, { columns: 3, children: COMPAT_SELECT_FIELDS.map(({ key, options }) => /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(Field, { label: t(key) ?? key, children: /* @__PURE__ */ (0, import_jsx_runtime4.jsx)(
      Select,
      {
        value: selectValue(key),
        options,
        allowUnset: true,
        unsetLabel: "\u2014",
        disabled,
        onChange: (value) => setSelect(key, value)
      }
    ) }, key)) })
  ] });
}

// src/client/components/AdvancedEditor.jsx
var import_react3 = require("react");
var import_jsx_runtime5 = require("react/jsx-runtime");
function AdvancedEditor({ store, t, route, entry, onToast, disabled }) {
  const [rawOpen, setRawOpen] = (0, import_react3.useState)(false);
  const toast = (result) => onToast?.(
    result.ok ? { tone: "good", text: t("applied") } : { tone: "bad", text: `${t("writeFailed")} ${result.message ?? t("unknownError")}` }
  );
  const write = async (suffix, value) => {
    const result = await store.writeRouteField(route, suffix, value);
    toast(result);
  };
  const unset = async (suffix) => {
    const result = await store.writeRouteField(route, suffix, void 0, { unset: true });
    toast(result);
  };
  const setNumber = (field, parsedOrNull) => {
    if (parsedOrNull === null) unset([field]);
    else write([field], parsedOrNull);
  };
  const headerRows = Object.entries(entry.headers ?? {});
  const [draftHeaders, setDraftHeaders] = (0, import_react3.useState)(
    () => headerRows.map(([key, value]) => ({ key, value: String(value) }))
  );
  const syncHeaders = (rows) => {
    setDraftHeaders(rows);
    const next = {};
    for (const row of rows) {
      const key = row.key.trim();
      if (key !== "") next[key] = row.value;
    }
    if (Object.keys(next).length === 0) unset(["headers"]);
    else write(["headers"], next);
  };
  return /* @__PURE__ */ (0, import_jsx_runtime5.jsxs)("div", { style: { display: "flex", flexDirection: "column", gap: 12 }, children: [
    /* @__PURE__ */ (0, import_jsx_runtime5.jsx)(Grid, { columns: 3, children: PROVIDER_NUMBER_FIELDS.map((field) => /* @__PURE__ */ (0, import_jsx_runtime5.jsx)(Field, { label: t(field) ?? field, children: /* @__PURE__ */ (0, import_jsx_runtime5.jsx)(
      NumberInput,
      {
        value: entry[field],
        disabled,
        onCommit: (parsed) => setNumber(field, parsed)
      }
    ) }, field)) }),
    /* @__PURE__ */ (0, import_jsx_runtime5.jsx)(Field, { label: t("headers"), children: /* @__PURE__ */ (0, import_jsx_runtime5.jsxs)("div", { style: { display: "flex", flexDirection: "column", gap: 6 }, children: [
      draftHeaders.map((row, index) => /* @__PURE__ */ (0, import_jsx_runtime5.jsxs)("div", { style: { display: "flex", gap: 8, alignItems: "center" }, children: [
        /* @__PURE__ */ (0, import_jsx_runtime5.jsx)(
          TextInput,
          {
            value: row.key,
            placeholder: t("headerKey"),
            disabled,
            onCommit: (key) => {
              const rows = draftHeaders.map((r, i) => i === index ? { ...r, key } : r);
              syncHeaders(rows);
            }
          }
        ),
        /* @__PURE__ */ (0, import_jsx_runtime5.jsx)(
          TextInput,
          {
            value: row.value,
            placeholder: t("headerValue"),
            disabled,
            onCommit: (value) => {
              const rows = draftHeaders.map((r, i) => i === index ? { ...r, value } : r);
              syncHeaders(rows);
            }
          }
        ),
        /* @__PURE__ */ (0, import_jsx_runtime5.jsx)(
          Btn,
          {
            kind: "danger",
            disabled,
            onClick: () => syncHeaders(draftHeaders.filter((_, i) => i !== index)),
            children: "\u2715"
          }
        )
      ] }, index)),
      /* @__PURE__ */ (0, import_jsx_runtime5.jsx)("div", { children: /* @__PURE__ */ (0, import_jsx_runtime5.jsxs)(
        Btn,
        {
          disabled,
          onClick: () => syncHeaders([...draftHeaders, { key: "", value: "" }]),
          children: [
            "+ ",
            t("addHeader")
          ]
        }
      ) })
    ] }) }),
    /* @__PURE__ */ (0, import_jsx_runtime5.jsxs)("div", { children: [
      /* @__PURE__ */ (0, import_jsx_runtime5.jsx)(Btn, { kind: "default", onClick: () => setRawOpen(!rawOpen), children: rawOpen ? `\u25BE ${t("rawView")}` : `\u25B8 ${t("rawView")}` }),
      rawOpen ? /* @__PURE__ */ (0, import_jsx_runtime5.jsx)(
        "pre",
        {
          style: {
            marginTop: 8,
            fontSize: 12,
            lineHeight: 1.5,
            overflow: "auto",
            maxHeight: 320,
            border: "1px solid color-mix(in srgb, currentColor 22%, transparent)",
            borderRadius: 8,
            padding: 10,
            whiteSpace: "pre-wrap",
            wordBreak: "break-all"
          },
          children: JSON.stringify(entry ?? {}, null, 2)
        }
      ) : null
    ] })
  ] });
}

// src/client/components/ModelEditor.jsx
var import_react4 = require("react");
var import_jsx_runtime6 = require("react/jsx-runtime");
var CAPACITY_FIELDS = ["contextWindow", "maxTokens"];
function ModelEditor({ store, t, route, model, onToast, disabled }) {
  const [confirmAll, setConfirmAll] = (0, import_react4.useState)(false);
  const modelId = model.id;
  const thinkingOff = model.reasoningEfforts === false;
  const efforts = thinkingOff || model.reasoningEfforts === void 0 ? {} : model.reasoningEfforts && typeof model.reasoningEfforts === "object" ? model.reasoningEfforts : {};
  const toast = (result, okKey, failKey) => {
    onToast?.(
      result.ok ? { tone: "good", text: t(okKey ?? "applied") } : { tone: "bad", text: `${t(failKey ?? "writeFailed")} ${result.message ?? t("unknownError")}` }
    );
  };
  const writeFields = async (fields) => {
    const result = await store.writeModelField(route, modelId, fields);
    toast(result);
  };
  const setCapacity = (field, parsedOrNull) => {
    const fields = {};
    fields[field] = parsedOrNull === null ? UNSET : parsedOrNull;
    writeFields(fields);
  };
  const setName = (text) => {
    writeFields({ name: text.trim() === "" ? UNSET : text });
  };
  const toggleInput = (modality, checked) => {
    const current = Array.isArray(model.input) ? model.input : [];
    const next = checked ? [...current, modality] : current.filter((m) => m !== modality);
    writeFields({ input: next });
  };
  const toggleThinking = (enabled) => {
    writeFields({ reasoningEfforts: enabled ? fullThinkingLevels() : false });
  };
  const setLevel = async (level, wireOrNull) => {
    const next = { ...efforts };
    if (wireOrNull === UNSET) delete next[level];
    else next[level] = wireOrNull;
    const nonOff = Object.entries(next).filter(([key, value]) => key !== "off" && typeof value === "string" && value.length > 0);
    if (nonOff.length === 0) {
      onToast?.({ tone: "bad", text: `${t("writeFailed")} ${t("reasoningNeedsOneLevel")}` });
      return;
    }
    const result = await store.writeModelField(route, modelId, { reasoningEfforts: next });
    toast(result);
  };
  const fillLevels = () => writeFields({ reasoningEfforts: fullThinkingLevels() });
  const applyToAll = async () => {
    const result = await store.applyModelToAll(route, modelId, [
      "name",
      ...CAPACITY_FIELDS,
      "input",
      "reasoningEfforts"
    ]);
    toast(result);
    setConfirmAll(false);
  };
  return /* @__PURE__ */ (0, import_jsx_runtime6.jsxs)(
    "div",
    {
      style: {
        border: border2,
        borderRadius: 8,
        padding: 12,
        display: "flex",
        flexDirection: "column",
        gap: 10
      },
      children: [
        /* @__PURE__ */ (0, import_jsx_runtime6.jsxs)("div", { style: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" }, children: [
          /* @__PURE__ */ (0, import_jsx_runtime6.jsx)("span", { style: { fontWeight: 600, wordBreak: "break-all" }, children: modelId }),
          thinkingOff ? /* @__PURE__ */ (0, import_jsx_runtime6.jsx)(Badge, { tone: "neutral", children: t("off") }) : null,
          /* @__PURE__ */ (0, import_jsx_runtime6.jsx)("span", { style: { flex: 1 } }),
          /* @__PURE__ */ (0, import_jsx_runtime6.jsx)(
            Btn,
            {
              kind: confirmAll ? "danger" : "default",
              onClick: () => confirmAll ? applyToAll() : setConfirmAll(true),
              title: t("applyToAllModels"),
              children: confirmAll ? `${t("applyToAllModels")} \u2713` : "\u21B3"
            }
          )
        ] }),
        /* @__PURE__ */ (0, import_jsx_runtime6.jsxs)(Grid, { columns: 3, children: [
          /* @__PURE__ */ (0, import_jsx_runtime6.jsx)(Field, { label: t("modelName"), children: /* @__PURE__ */ (0, import_jsx_runtime6.jsx)(
            TextInput,
            {
              value: model.name ?? "",
              placeholder: modelId,
              onCommit: setName,
              disabled
            }
          ) }),
          /* @__PURE__ */ (0, import_jsx_runtime6.jsx)(Field, { label: t("contextWindow"), hint: t("capacityHint"), children: /* @__PURE__ */ (0, import_jsx_runtime6.jsx)(
            CapacityInput,
            {
              value: model.contextWindow,
              onCommit: (parsed) => setCapacity("contextWindow", parsed),
              disabled
            }
          ) }),
          /* @__PURE__ */ (0, import_jsx_runtime6.jsx)(Field, { label: t("maxTokens"), hint: t("capacityHint"), children: /* @__PURE__ */ (0, import_jsx_runtime6.jsx)(
            CapacityInput,
            {
              value: model.maxTokens,
              onCommit: (parsed) => setCapacity("maxTokens", parsed),
              disabled
            }
          ) })
        ] }),
        /* @__PURE__ */ (0, import_jsx_runtime6.jsxs)(Grid, { columns: 2, children: [
          /* @__PURE__ */ (0, import_jsx_runtime6.jsx)(Field, { label: t("inputModalities"), children: /* @__PURE__ */ (0, import_jsx_runtime6.jsx)("div", { style: { display: "flex", gap: 16, flexWrap: "wrap" }, children: MODALITIES.map((modality) => /* @__PURE__ */ (0, import_jsx_runtime6.jsx)(
            Check,
            {
              label: t(modality === "text" ? "modalityText" : "modalityImage"),
              checked: Array.isArray(model.input) && model.input.includes(modality),
              disabled,
              onChange: (checked) => toggleInput(modality, checked)
            },
            modality
          )) }) }),
          /* @__PURE__ */ (0, import_jsx_runtime6.jsx)(Field, { label: t("thinkingEnabled"), children: /* @__PURE__ */ (0, import_jsx_runtime6.jsx)(
            Check,
            {
              label: t("thinkingEnabled"),
              checked: !thinkingOff,
              disabled,
              onChange: toggleThinking,
              hint: thinkingOff ? t("reasoningFalseHint") : void 0
            }
          ) })
        ] }),
        !thinkingOff ? /* @__PURE__ */ (0, import_jsx_runtime6.jsxs)("div", { style: { display: "flex", flexDirection: "column", gap: 6 }, children: [
          /* @__PURE__ */ (0, import_jsx_runtime6.jsx)("div", { style: { fontSize: 12, opacity: 0.7 }, children: t("thinkingHint") }),
          /* @__PURE__ */ (0, import_jsx_runtime6.jsx)("div", { style: { display: "flex", flexDirection: "column", gap: 4 }, children: THINKING_LEVELS.map((level) => {
            const raw = efforts[level];
            const value = raw === void 0 || raw === null ? "" : String(raw);
            const isOff = level === "off";
            return /* @__PURE__ */ (0, import_jsx_runtime6.jsxs)("div", { style: { display: "flex", alignItems: "center", gap: 8 }, children: [
              /* @__PURE__ */ (0, import_jsx_runtime6.jsx)("span", { style: { width: 110, fontSize: 13, opacity: 0.9, flexShrink: 0 }, children: t(`level${level[0].toUpperCase()}${level.slice(1)}`) }),
              /* @__PURE__ */ (0, import_jsx_runtime6.jsx)(
                TextInput,
                {
                  value,
                  placeholder: isOff ? t("offPlaceholder") : t("wirePlaceholder"),
                  disabled,
                  onCommit: (text) => setLevel(
                    level,
                    text.trim() === "" ? isOff ? null : UNSET : text
                  ),
                  width: "100%"
                }
              ),
              isOff ? /* @__PURE__ */ (0, import_jsx_runtime6.jsx)("span", { style: { fontSize: 11, opacity: 0.5 }, children: t("offPlaceholder") }) : null
            ] }, level);
          }) }),
          /* @__PURE__ */ (0, import_jsx_runtime6.jsx)("div", { children: /* @__PURE__ */ (0, import_jsx_runtime6.jsx)(Btn, { onClick: fillLevels, disabled, title: t("fillLevels"), children: t("fillLevels") }) })
        ] }) : null,
        /* @__PURE__ */ (0, import_jsx_runtime6.jsx)(Fold, { title: t("modelCompat"), defaultOpen: false, children: /* @__PURE__ */ (0, import_jsx_runtime6.jsx)(
          CompatEditor,
          {
            store,
            t,
            route,
            suffixPath: ["models", modelIndexFor(store, route, modelId)],
            compat: model.compat,
            onToast,
            disabled
          }
        ) })
      ]
    }
  );
}
function modelIndexFor(store, route, modelId) {
  const index = store.modelIndexById(route, modelId);
  return index < 0 ? 0 : index;
}
var border2 = "1px solid color-mix(in srgb, currentColor 22%, transparent)";

// src/client/components/RouteCard.jsx
var import_jsx_runtime7 = require("react/jsx-runtime");
function RouteCard({ store, t, route, onToast, disabled, defaultOpen }) {
  const entry = store.route(route);
  if (entry === void 0) return null;
  const toast = (result) => onToast?.(
    result.ok ? { tone: "good", text: t("applied") } : { tone: "bad", text: `${t("writeFailed")} ${result.message ?? t("unknownError")}` }
  );
  const write = async (suffix, value) => {
    const result = await store.writeRouteField(route, suffix, value);
    toast(result);
  };
  const unset = async (suffix) => {
    const result = await store.writeRouteField(route, suffix, void 0, { unset: true });
    toast(result);
  };
  const legacyBad = looksLikeLegacyGateway(entry.baseURL) && entry.compat?.supportsDeveloperRole === true;
  const models = store.modelsOf(route);
  const modernGateway = looksLikeLegacyGateway(entry.baseURL) && entry.compat?.supportsDeveloperRole === false;
  return /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(
    Fold,
    {
      title: entry.displayName || route,
      badge: /* @__PURE__ */ (0, import_jsx_runtime7.jsxs)("span", { style: { display: "inline-flex", gap: 4, alignItems: "center" }, children: [
        legacyBad ? /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(Badge, { tone: "warn", children: "!compat" }) : null,
        modernGateway ? /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(Badge, { tone: "neutral", children: t("off") }) : null,
        /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(Badge, { tone: "neutral", children: `${models.length} ${t("model")}` })
      ] }),
      defaultOpen,
      children: /* @__PURE__ */ (0, import_jsx_runtime7.jsxs)("div", { style: { display: "flex", flexDirection: "column", gap: 12 }, children: [
        /* @__PURE__ */ (0, import_jsx_runtime7.jsxs)(Grid, { columns: 3, children: [
          /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(Field, { label: t("displayName"), children: /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(
            TextInput,
            {
              value: entry.displayName ?? "",
              placeholder: route,
              onCommit: (value) => value.trim() === "" ? unset(["displayName"]) : write(["displayName"], value),
              disabled
            }
          ) }),
          /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(Field, { label: t("baseURL"), children: /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(
            TextInput,
            {
              value: entry.baseURL ?? "",
              onCommit: (value) => value.trim() === "" ? unset(["baseURL"]) : write(["baseURL"], value),
              disabled
            }
          ) }),
          /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(Field, { label: t("api"), children: /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(
            Select,
            {
              value: entry.api,
              options: APIS,
              allowUnset: true,
              unsetLabel: "\u2014",
              disabled,
              onChange: (value) => value === void 0 ? unset(["api"]) : write(["api"], value)
            }
          ) })
        ] }),
        /* @__PURE__ */ (0, import_jsx_runtime7.jsxs)("div", { style: { fontSize: 12, opacity: 0.6 }, children: [
          t("routeId"),
          ": ",
          /* @__PURE__ */ (0, import_jsx_runtime7.jsx)("code", { style: { wordBreak: "break-all" }, children: route }),
          entry.apiKeyEnv ? /* @__PURE__ */ (0, import_jsx_runtime7.jsxs)(import_jsx_runtime7.Fragment, { children: [
            " \xB7 ",
            t("apiKeyEnv"),
            ": ",
            /* @__PURE__ */ (0, import_jsx_runtime7.jsx)("code", { children: entry.apiKeyEnv })
          ] }) : null
        ] }),
        /* @__PURE__ */ (0, import_jsx_runtime7.jsxs)("div", { style: { display: "flex", flexDirection: "column", gap: 10 }, children: [
          /* @__PURE__ */ (0, import_jsx_runtime7.jsx)("div", { style: { fontSize: 12, opacity: 0.7, fontWeight: 600 }, children: `${models.length} ${t("model")}` }),
          models.length === 0 ? /* @__PURE__ */ (0, import_jsx_runtime7.jsx)("div", { style: { fontSize: 12, opacity: 0.6 }, children: t("diagNoModels").replace("{route}", route) }) : models.map(
            (model) => model && typeof model.id === "string" ? /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(
              ModelEditor,
              {
                store,
                t,
                route,
                model,
                onToast,
                disabled
              },
              model.id
            ) : null
          )
        ] }),
        /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(Fold, { title: t("defaultsTitle"), children: /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(DefaultsEditor, { store, t, route, entry, onToast, disabled }) }),
        /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(Fold, { title: t("compatTitle"), children: /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(
          CompatEditor,
          {
            store,
            t,
            route,
            suffixPath: [],
            compat: entry.compat,
            onToast,
            disabled
          }
        ) }),
        /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(Fold, { title: t("advancedFold"), children: /* @__PURE__ */ (0, import_jsx_runtime7.jsx)(AdvancedEditor, { store, t, route, entry, onToast, disabled }) })
      ] })
    }
  );
}

// src/client/components/Section.jsx
var import_jsx_runtime8 = require("react/jsx-runtime");
var dicts = { en, zh };
function useScope(scope) {
  return (0, import_react5.useSyncExternalStore)(
    (callback) => scope.subscribe(callback),
    () => scope.getSnapshot(),
    () => scope.getSnapshot()
  );
}
function Section({ store, owner }) {
  const [toast, setToast] = (0, import_react5.useState)(null);
  useScope(store.llmScope);
  useScope(store.selfScope);
  const lang = store.effectiveLanguage();
  const t = (key, params) => localize(dicts, lang, key, params);
  const disabled = !store.writable();
  const snap = store.llmSnapshot();
  const notify = (next) => {
    setToast(next);
    if (next?.tone === "good") {
      window.setTimeout(() => setToast((current) => current === next ? null : current), 2600);
    }
  };
  const routes = store.routeNames();
  const diagnostics = computeDiagnostics(t, store);
  const language = store.selfSnapshot().value?.language ?? "follow";
  return /* @__PURE__ */ (0, import_jsx_runtime8.jsxs)(
    "div",
    {
      style: {
        display: "flex",
        flexDirection: "column",
        gap: 14,
        maxWidth: 980,
        paddingBottom: 48
      },
      children: [
        /* @__PURE__ */ (0, import_jsx_runtime8.jsxs)("div", { style: { display: "flex", alignItems: "center", gap: 12, flexWrap: "wrap" }, children: [
          /* @__PURE__ */ (0, import_jsx_runtime8.jsx)("div", { style: { fontSize: 13, opacity: 0.75, flex: 1 }, children: t("pageIntro") }),
          /* @__PURE__ */ (0, import_jsx_runtime8.jsxs)("label", { style: { display: "flex", alignItems: "center", gap: 8 }, children: [
            /* @__PURE__ */ (0, import_jsx_runtime8.jsx)("span", { style: { fontSize: 12, opacity: 0.75 }, children: t("langField") }),
            /* @__PURE__ */ (0, import_jsx_runtime8.jsx)(
              Select,
              {
                value: language,
                options: [
                  { value: "follow", label: t("langFollow") },
                  { value: "en", label: t("langEn") },
                  { value: "zh", label: t("langZh") }
                ],
                onChange: (value) => store.setLanguage(value === void 0 ? "follow" : value)
              }
            )
          ] })
        ] }),
        /* @__PURE__ */ (0, import_jsx_runtime8.jsxs)("div", { style: { display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap" }, children: [
          store.writable() ? /* @__PURE__ */ (0, import_jsx_runtime8.jsx)(Badge, { tone: "good", children: t("writableHost") }) : null,
          !store.writable() ? /* @__PURE__ */ (0, import_jsx_runtime8.jsx)(Badge, { tone: "warn", children: t("notWritable") }) : null,
          snap.mode === "memory" ? /* @__PURE__ */ (0, import_jsx_runtime8.jsx)(Badge, { tone: "warn", children: t("memoryMode") }) : null
        ] }),
        /* @__PURE__ */ (0, import_jsx_runtime8.jsx)(Toast, { toast }),
        diagnostics.length > 0 ? /* @__PURE__ */ (0, import_jsx_runtime8.jsxs)("div", { style: { display: "flex", flexDirection: "column", gap: 6 }, children: [
          /* @__PURE__ */ (0, import_jsx_runtime8.jsx)("div", { style: { fontSize: 12, opacity: 0.7, fontWeight: 600 }, children: t("diagTitle") }),
          diagnostics.map((item, i) => /* @__PURE__ */ (0, import_jsx_runtime8.jsx)(WarningBox, { tone: item.tone, children: item.text }, i))
        ] }) : /* @__PURE__ */ (0, import_jsx_runtime8.jsx)("div", { style: { fontSize: 12, opacity: 0.55 }, children: t("diagNone") }),
        /* @__PURE__ */ (0, import_jsx_runtime8.jsx)("div", { style: { border: "1px solid color-mix(in srgb, currentColor 22%, transparent)", borderRadius: 10, padding: 14 }, children: /* @__PURE__ */ (0, import_jsx_runtime8.jsx)(PresetBar, { store, t, routes, onToast: notify, disabled }) }),
        /* @__PURE__ */ (0, import_jsx_runtime8.jsx)("div", { style: { fontSize: 12, opacity: 0.7, fontWeight: 600 }, children: `${routes.length} ${t("route")}` }),
        /* @__PURE__ */ (0, import_jsx_runtime8.jsxs)("div", { style: { display: "flex", flexDirection: "column", gap: 10 }, children: [
          routes.map((route, index) => /* @__PURE__ */ (0, import_jsx_runtime8.jsx)(
            RouteCard,
            {
              store,
              t,
              route,
              onToast: notify,
              disabled,
              defaultOpen: index === 0
            },
            route
          )),
          routes.length === 0 ? /* @__PURE__ */ (0, import_jsx_runtime8.jsxs)("div", { style: { fontSize: 13, opacity: 0.65 }, children: [
            t("routeNotFound"),
            " \u2014 settings.yaml (llm-pi-ai.providers)"
          ] }) : null
        ] })
      ]
    }
  );
}
function computeDiagnostics(t, store) {
  const out = [];
  const providers = store.providers();
  for (const [route, entry] of Object.entries(providers)) {
    if (!entry || typeof entry !== "object") continue;
    if (looksLikeLegacyGateway(entry.baseURL) && entry.compat?.supportsDeveloperRole === true) {
      out.push({ tone: "warn", text: t("diagDeveloperRole").replace("{route}", route) });
    }
    const models = Array.isArray(entry.models) ? entry.models : [];
    for (const model of models) {
      if (!model || typeof model.id !== "string") continue;
      const label = `${route} / ${model.id}`;
      if (model.reasoningEfforts !== false && model.reasoningEfforts) {
        for (const level of THINKING_LEVELS) {
          const value = model.reasoningEfforts[level];
          if (level !== "off" && (value === null || value === "")) {
            out.push({
              tone: "warn",
              text: t("diagEmptyEffort").replace("{route}", route).replace("{model}", model.id).replace("{level}", level)
            });
          }
        }
      }
      if (model.contextWindow === void 0) {
        out.push({ tone: "info", text: t("diagNoContext").replace("{route}", route).replace("{model}", model.id) });
      }
    }
    if (models.length === 0) {
      out.push({ tone: "info", text: t("diagNoModels").replace("{route}", route) });
    }
  }
  return out;
}

// src/client/index.jsx
var NS2 = "settings.model-capability";
var inject = [
  "slots",
  "locale",
  "connection",
  "remote",
  "settingsScope",
  "settingsSchema"
];
function apply(ctx) {
  ctx.effect(
    () => ctx.locale.register(NS2, { zh, en }),
    "model-capability: copy dictionaries"
  );
  const t = ctx.locale.bind(NS2);
  const connection = ctx.get("connection");
  const locale = ctx.get("locale");
  const settingsScope = ctx.get("settingsScope");
  const llmScope = settingsScope.bind({ namespace: "llm-pi-ai" });
  const selfScope = settingsScope.bind({ namespace: "model-capability" });
  const store = new CapabilityStore({
    api: connection.api,
    llmScope,
    selfScope,
    locale
  });
  ctx.slots.inject(
    "settings.section",
    () => ctx.slots.register(
      {
        name: "settings.section",
        id: "model-capability",
        order: 11,
        label: () => t("nav"),
        inject: () => ({ store })
      },
      Section
    )
  );
}
		return module.exports;
	}
});
