// Build script for dsh-plugin-model-capability.
//
//   - src/host/index.js    → lib/index.js    (Node/ESM, copied verbatim)
//   - src/client/index.jsx → lib/client.js  (browser bundle wrapped in the
//     window.__ModuleLoader__.load({ id, factory }) registration the DSH web
//     shell expects — same shape every shipped @deepseek-ai client bundle uses)
//
// The client bundle is produced by the esbuild CLI writing directly to the
// output file with stdio inherited — no pipe capture, so the script works in
// sandboxed environments and never depends on spawning esbuild with captured
// output. The `load()` wrapper is applied through --banner / --footer.
//
// Run with: npm run build   (requires esbuild in devDependencies)

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));

const banner = [
  "// Generated by scripts/build.mjs — do not edit.",
  "window.__ModuleLoader__.load({",
  `\tid: ${JSON.stringify(pkg.name)},`,
  "\tfactory: (require) => {",
  "\t\tvar module = { exports: {} };",
  "\t\tvar exports = module.exports;",
].join("\n");

const footer = ["\t\treturn module.exports;", "\t}", "});"].join("\n");

// esbuild's JS wrapper inherits stdio (no pipe capture) and spawns the
// platform binary the same way, so the whole chain stays sandbox-friendly.
const esbuildCli = join(root, "node_modules", "esbuild", "bin", "esbuild");

const args = [
  esbuildCli,
  join(root, "src/client/index.jsx"),
  "--bundle",
  "--format=cjs",
  "--platform=browser",
  "--target=es2022",
  "--jsx=automatic",
  "--external:react",
  "--external:react/jsx-runtime",
  "--external:@deepseek-ai/cordis",
  `--banner:js=${banner}`,
  `--footer:js=${footer}`,
  `--outfile=${join(root, "lib/client.js")}`,
  "--log-level=warning",
];

const result = spawnSync(process.execPath, args, { stdio: "inherit", cwd: root });
if (result.error) {
  console.error("failed to run esbuild CLI:", result.error.message);
  process.exit(1);
}
if (result.status !== 0) process.exit(result.status ?? 1);

mkdirSync(join(root, "lib"), { recursive: true });
writeFileSync(
  join(root, "lib/index.js"),
  readFileSync(join(root, "src/host/index.js"), "utf8"),
  "utf8",
);

console.log(`built ${pkg.name} v${pkg.version}`);
console.log("  lib/client.js  (web client bundle)");
console.log("  lib/index.js   (host half)");